title: Bible Commentary
url: "https://benmichael.github.io"
baseurl: "/BibleCommentary"
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
