title: Bible Commentary
url: "https://benmichael.github.io"
baseurl: "/BibleCommentary"
remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
