title: Bible Commentary
url: "https://benmichael.github.io"
baseurl: "/BibleCommentary"
theme: midnight

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-relative-links
